# This file was generated by go2nix.
[
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "3da985ce5951d99de868be4385f21ea6c2b22f24";
      sha256 = "0mhqa53pyj9gxg4m0c9s0f4r5jp0rihlni1nrpkd1d921xxzh714";
    };
  }
]

